[profile.default]
src = "contracts"
test = "test/foundry"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 10000
verbosity = 3
via_ir = true

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true 
