[profile.default]
# Point Foundry to the existing contract sources and OpenZeppelin in node_modules
src = "./contracts"
test = "./foundry/test"
libs = ["lib", "node_modules"]

# Solidity compiler
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings so both OZ & forge-std imports resolve
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]

# Keep artifacts separate from Hardhat
out = "foundry/out"
cache_path = "foundry/cache"
