site_name: Lockx documentation
site_url: https://docs.lockx.io
repo_url: https://github.com/richardjaee/Lockx-Contracts
edit_uri: ''

theme:
  name: material
  font:
    text: Inter
    code: Fira Code
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.top
extra_css:
  - stylesheets/extra.css

nav:
  - Overview: index.md
  - Getting started:
      - Introduction: getting-started/introduction.md
      - Quick start: getting-started/quick-start.md
  - Smart contracts:
      - Contract overview: smart-contracts/overview.md
      - Lockx contract: smart-contracts/lockx.md
      - Deposits contract: smart-contracts/deposits.md
      - Withdrawals contract: smart-contracts/withdrawals.md
      - Signature verification: smart-contracts/signature-verification.md
  - Lockbox:
      - Secure asset storage: lockbox/secure-asset-storage.md
      - Soulbound nature: lockbox/soulbound.md
      - Multi-asset support: lockbox/multi-asset-support.md
  - Security benefits:
      - Wallet attack protection: security-benefits/wallet-attack-protection.md
      - Contract attack protection: security-benefits/contract-attack-protection.md
  - Key management:
      - Key fraction technology: key-management/key-fraction.md
      - 2FA protection: key-management/twofa.md
      - Self custody signing: key-management/self-custody-signing.md
      - Key rotation: key-management/key-rotation.md
  - Security & authorization:
      - EIP-712 signatures: security-authorization/eip-712.md
      - Security measures: security-authorization/security-measures.md
      - Direct contract interaction: security-authorization/direct-interaction.md
  - FAQ & support:
      - FAQs: faq-support/faq.md
      - Troubleshooting: faq-support/troubleshooting.md
      - Contact support: faq-support/contact-support.md
  - Audit report: AUDIT_REPORT_v1.0.0.md
  - Test methodology: test-report-detailed-2025-06-23.md
  - API reference:
      - Lockx: api/Lockx.md
      - Deposits: api/Deposits.md
      - Withdrawals: api/Withdrawals.md
      - SignatureVerification: api/SignatureVerification.md
