name: ci

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: run unit tests
        run: npm run test

      - name: generate coverage report
        run: npm run coverage

      - name: set up foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: run foundry tests
        run: forge test -vv

      - name: generate gas report
        run: npm run gas:report

      - name: upload gas report artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: reports/gas-report.txt

      - name: set up python for slither
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install slither
        run: |
          pip install slither-analyzer==0.11.1

      - name: run slither
        run: npm run slither

      - name: install mythril
        run: |
          pip install mythril

      - name: run mythril analysis
        run: npm run mythril
        continue-on-error: true
