name: docs

on:
  push:
    branches: ["main", "master"]
    paths:
      - 'contracts/**/*.sol'
      - '.github/workflows/docs.yml'
      - 'package.json'
      - 'hardhat.config.ts'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate docs
        run: npm run docs
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
