name: docs

on:
  push:
    branches: ["main", "master"]
    paths:
      - 'contracts/**/*.sol'
      - '.github/workflows/docs.yml'
      - 'package.json'
      - 'hardhat.config.ts'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Node deps
        run: npm ci

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material pygments mkdocs-markdownextradata-plugin
      - name: Generate API markdown (solidity-docgen)
        run: npm run docs
      - name: Build MkDocs site
        run: mkdocs build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
