name: echidna

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

jobs:
  echidna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          contract: EchidnaLockxInvariant.sol:EchidnaLockxInvariant
          source: echidna
          solc-version: '0.8.30'
          runs: 1000
          config: echidna.yaml
        continue-on-error: true
